export const CURRENCY_CODE = {
  USD: {
    symbol: "$",
    name: "US Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "USD",
    name_plural: "US dollars",
  },
  EUR: {
    symbol: "€",
    name: "Euro",
    symbol_native: "€",
    decimal_digits: 2,
    rounding: 0,
    code: "EUR",
    name_plural: "euros",
  },
  XAF: {
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    symbol_native: "FCFA",
    decimal_digits: 0,
    rounding: 0,
    code: "XAF",
    name_plural: "CFA francs BEAC",
  },
 /* CAD: {
    symbol: "CA$",
    name: "Canadian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "CAD",
    name_plural: "Canadian dollars",
  },

  AED: {
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    symbol_native: "د.إ.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "AED",
    name_plural: "UAE dirhams",
  },
  AFN: {
    symbol: "Af",
    name: "Afghan Afghani",
    symbol_native: "؋",
    decimal_digits: 0,
    rounding: 0,
    code: "AFN",
    name_plural: "Afghan Afghanis",
  },
  ALL: {
    symbol: "ALL",
    name: "Albanian Lek",
    symbol_native: "Lek",
    decimal_digits: 0,
    rounding: 0,
    code: "ALL",
    name_plural: "Albanian lekë",
  },
  AMD: {
    symbol: "AMD",
    name: "Armenian Dram",
    symbol_native: "դր.",
    decimal_digits: 0,
    rounding: 0,
    code: "AMD",
    name_plural: "Armenian drams",
  },
  ARS: {
    symbol: "AR$",
    name: "Argentine Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "ARS",
    name_plural: "Argentine pesos",
  },
  AUD: {
    symbol: "AU$",
    name: "Australian Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "AUD",
    name_plural: "Australian dollars",
  },
  AZN: {
    symbol: "man.",
    name: "Azerbaijani Manat",
    symbol_native: "ман.",
    decimal_digits: 2,
    rounding: 0,
    code: "AZN",
    name_plural: "Azerbaijani manats",
  },
  BAM: {
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol_native: "KM",
    decimal_digits: 2,
    rounding: 0,
    code: "BAM",
    name_plural: "Bosnia-Herzegovina convertible marks",
  },
  BDT: {
    symbol: "Tk",
    name: "Bangladeshi Taka",
    symbol_native: "৳",
    decimal_digits: 2,
    rounding: 0,
    code: "BDT",
    name_plural: "Bangladeshi takas",
  },
  BGN: {
    symbol: "BGN",
    name: "Bulgarian Lev",
    symbol_native: "лв.",
    decimal_digits: 2,
    rounding: 0,
    code: "BGN",
    name_plural: "Bulgarian leva",
  },
  BHD: {
    symbol: "BD",
    name: "Bahraini Dinar",
    symbol_native: "د.ب.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "BHD",
    name_plural: "Bahraini dinars",
  },
  BIF: {
    symbol: "FBu",
    name: "Burundian Franc",
    symbol_native: "FBu",
    decimal_digits: 0,
    rounding: 0,
    code: "BIF",
    name_plural: "Burundian francs",
  },
  BND: {
    symbol: "BN$",
    name: "Brunei Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BND",
    name_plural: "Brunei dollars",
  },
  BOB: {
    symbol: "Bs",
    name: "Bolivian Boliviano",
    symbol_native: "Bs",
    decimal_digits: 2,
    rounding: 0,
    code: "BOB",
    name_plural: "Bolivian bolivianos",
  },
  BRL: {
    symbol: "R$",
    name: "Brazilian Real",
    symbol_native: "R$",
    decimal_digits: 2,
    rounding: 0,
    code: "BRL",
    name_plural: "Brazilian reals",
  },
  BWP: {
    symbol: "BWP",
    name: "Botswanan Pula",
    symbol_native: "P",
    decimal_digits: 2,
    rounding: 0,
    code: "BWP",
    name_plural: "Botswanan pulas",
  },
  BYN: {
    symbol: "Br",
    name: "Belarusian Ruble",
    symbol_native: "руб.",
    decimal_digits: 2,
    rounding: 0,
    code: "BYN",
    name_plural: "Belarusian rubles",
  },
  BZD: {
    symbol: "BZ$",
    name: "Belize Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "BZD",
    name_plural: "Belize dollars",
  },
  CDF: {
    symbol: "CDF",
    name: "Congolese Franc",
    symbol_native: "FrCD",
    decimal_digits: 2,
    rounding: 0,
    code: "CDF",
    name_plural: "Congolese francs",
  },
  CHF: {
    symbol: "CHF",
    name: "Swiss Franc",
    symbol_native: "CHF",
    decimal_digits: 2,
    rounding: 0.05,
    code: "CHF",
    name_plural: "Swiss francs",
  },
  CLP: {
    symbol: "CL$",
    name: "Chilean Peso",
    symbol_native: "$",
    decimal_digits: 0,
    rounding: 0,
    code: "CLP",
    name_plural: "Chilean pesos",
  },
  CNY: {
    symbol: "CN¥",
    name: "Chinese Yuan",
    symbol_native: "CN¥",
    decimal_digits: 2,
    rounding: 0,
    code: "CNY",
    name_plural: "Chinese yuan",
  },
  COP: {
    symbol: "CO$",
    name: "Colombian Peso",
    symbol_native: "$",
    decimal_digits: 0,
    rounding: 0,
    code: "COP",
    name_plural: "Colombian pesos",
  },
  CRC: {
    symbol: "₡",
    name: "Costa Rican Colón",
    symbol_native: "₡",
    decimal_digits: 0,
    rounding: 0,
    code: "CRC",
    name_plural: "Costa Rican colóns",
  },
  CVE: {
    symbol: "CV$",
    name: "Cape Verdean Escudo",
    symbol_native: "CV$",
    decimal_digits: 2,
    rounding: 0,
    code: "CVE",
    name_plural: "Cape Verdean escudos",
  },
  CZK: {
    symbol: "Kč",
    name: "Czech Republic Koruna",
    symbol_native: "Kč",
    decimal_digits: 2,
    rounding: 0,
    code: "CZK",
    name_plural: "Czech Republic korunas",
  },
  DJF: {
    symbol: "Fdj",
    name: "Djiboutian Franc",
    symbol_native: "Fdj",
    decimal_digits: 0,
    rounding: 0,
    code: "DJF",
    name_plural: "Djiboutian francs",
  },
  DKK: {
    symbol: "Dkr",
    name: "Danish Krone",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "DKK",
    name_plural: "Danish kroner",
  },
  DOP: {
    symbol: "RD$",
    name: "Dominican Peso",
    symbol_native: "RD$",
    decimal_digits: 2,
    rounding: 0,
    code: "DOP",
    name_plural: "Dominican pesos",
  },
  DZD: {
    symbol: "DA",
    name: "Algerian Dinar",
    symbol_native: "د.ج.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "DZD",
    name_plural: "Algerian dinars",
  },
  EEK: {
    symbol: "Ekr",
    name: "Estonian Kroon",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "EEK",
    name_plural: "Estonian kroons",
  },
  EGP: {
    symbol: "EGP",
    name: "Egyptian Pound",
    symbol_native: "ج.م.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "EGP",
    name_plural: "Egyptian pounds",
  },
  ERN: {
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    symbol_native: "Nfk",
    decimal_digits: 2,
    rounding: 0,
    code: "ERN",
    name_plural: "Eritrean nakfas",
  },
  ETB: {
    symbol: "Br",
    name: "Ethiopian Birr",
    symbol_native: "Br",
    decimal_digits: 2,
    rounding: 0,
    code: "ETB",
    name_plural: "Ethiopian birrs",
  },
  GBP: {
    symbol: "£",
    name: "British Pound Sterling",
    symbol_native: "£",
    decimal_digits: 2,
    rounding: 0,
    code: "GBP",
    name_plural: "British pounds sterling",
  },
  GEL: {
    symbol: "GEL",
    name: "Georgian Lari",
    symbol_native: "GEL",
    decimal_digits: 2,
    rounding: 0,
    code: "GEL",
    name_plural: "Georgian laris",
  },
  GHS: {
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    symbol_native: "GH₵",
    decimal_digits: 2,
    rounding: 0,
    code: "GHS",
    name_plural: "Ghanaian cedis",
  },
  GNF: {
    symbol: "FG",
    name: "Guinean Franc",
    symbol_native: "FG",
    decimal_digits: 0,
    rounding: 0,
    code: "GNF",
    name_plural: "Guinean francs",
  },
  GTQ: {
    symbol: "GTQ",
    name: "Guatemalan Quetzal",
    symbol_native: "Q",
    decimal_digits: 2,
    rounding: 0,
    code: "GTQ",
    name_plural: "Guatemalan quetzals",
  },
  HKD: {
    symbol: "HK$",
    name: "Hong Kong Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "HKD",
    name_plural: "Hong Kong dollars",
  },
  HNL: {
    symbol: "HNL",
    name: "Honduran Lempira",
    symbol_native: "L",
    decimal_digits: 2,
    rounding: 0,
    code: "HNL",
    name_plural: "Honduran lempiras",
  },
  HRK: {
    symbol: "kn",
    name: "Croatian Kuna",
    symbol_native: "kn",
    decimal_digits: 2,
    rounding: 0,
    code: "HRK",
    name_plural: "Croatian kunas",
  },
  HUF: {
    symbol: "Ft",
    name: "Hungarian Forint",
    symbol_native: "Ft",
    decimal_digits: 0,
    rounding: 0,
    code: "HUF",
    name_plural: "Hungarian forints",
  },
  IDR: {
    symbol: "Rp",
    name: "Indonesian Rupiah",
    symbol_native: "Rp",
    decimal_digits: 0,
    rounding: 0,
    code: "IDR",
    name_plural: "Indonesian rupiahs",
  },
  ILS: {
    symbol: "₪",
    name: "Israeli New Sheqel",
    symbol_native: "₪",
    decimal_digits: 2,
    rounding: 0,
    code: "ILS",
    name_plural: "Israeli new sheqels",
  },
  INR: {
    symbol: "Rs",
    name: "Indian Rupee",
    symbol_native: "টকা",
    decimal_digits: 2,
    rounding: 0,
    code: "INR",
    name_plural: "Indian rupees",
  },
  IQD: {
    symbol: "IQD",
    name: "Iraqi Dinar",
    symbol_native: "د.ع.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "IQD",
    name_plural: "Iraqi dinars",
  },
  IRR: {
    symbol: "IRR",
    name: "Iranian Rial",
    symbol_native: "﷼",
    decimal_digits: 0,
    rounding: 0,
    code: "IRR",
    name_plural: "Iranian rials",
  },
  ISK: {
    symbol: "Ikr",
    name: "Icelandic Króna",
    symbol_native: "kr",
    decimal_digits: 0,
    rounding: 0,
    code: "ISK",
    name_plural: "Icelandic krónur",
  },
  JMD: {
    symbol: "J$",
    name: "Jamaican Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "JMD",
    name_plural: "Jamaican dollars",
  },
  JOD: {
    symbol: "JD",
    name: "Jordanian Dinar",
    symbol_native: "د.أ.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "JOD",
    name_plural: "Jordanian dinars",
  },
  JPY: {
    symbol: "¥",
    name: "Japanese Yen",
    symbol_native: "￥",
    decimal_digits: 0,
    rounding: 0,
    code: "JPY",
    name_plural: "Japanese yen",
  },
  KES: {
    symbol: "Ksh",
    name: "Kenyan Shilling",
    symbol_native: "Ksh",
    decimal_digits: 2,
    rounding: 0,
    code: "KES",
    name_plural: "Kenyan shillings",
  },
  KHR: {
    symbol: "KHR",
    name: "Cambodian Riel",
    symbol_native: "៛",
    decimal_digits: 2,
    rounding: 0,
    code: "KHR",
    name_plural: "Cambodian riels",
  },
  KMF: {
    symbol: "CF",
    name: "Comorian Franc",
    symbol_native: "FC",
    decimal_digits: 0,
    rounding: 0,
    code: "KMF",
    name_plural: "Comorian francs",
  },
  KRW: {
    symbol: "₩",
    name: "South Korean Won",
    symbol_native: "₩",
    decimal_digits: 0,
    rounding: 0,
    code: "KRW",
    name_plural: "South Korean won",
  },
  KWD: {
    symbol: "KD",
    name: "Kuwaiti Dinar",
    symbol_native: "د.ك.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "KWD",
    name_plural: "Kuwaiti dinars",
  },
  KZT: {
    symbol: "KZT",
    name: "Kazakhstani Tenge",
    symbol_native: "тңг.",
    decimal_digits: 2,
    rounding: 0,
    code: "KZT",
    name_plural: "Kazakhstani tenges",
  },
  LBP: {
    symbol: "L.L.",
    name: "Lebanese Pound",
    symbol_native: "ل.ل.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "LBP",
    name_plural: "Lebanese pounds",
  },
  LKR: {
    symbol: "SLRs",
    name: "Sri Lankan Rupee",
    symbol_native: "SL Re",
    decimal_digits: 2,
    rounding: 0,
    code: "LKR",
    name_plural: "Sri Lankan rupees",
  },
  LTL: {
    symbol: "Lt",
    name: "Lithuanian Litas",
    symbol_native: "Lt",
    decimal_digits: 2,
    rounding: 0,
    code: "LTL",
    name_plural: "Lithuanian litai",
  },
  LVL: {
    symbol: "Ls",
    name: "Latvian Lats",
    symbol_native: "Ls",
    decimal_digits: 2,
    rounding: 0,
    code: "LVL",
    name_plural: "Latvian lati",
  },
  LYD: {
    symbol: "LD",
    name: "Libyan Dinar",
    symbol_native: "د.ل.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "LYD",
    name_plural: "Libyan dinars",
  },
  MAD: {
    symbol: "MAD",
    name: "Moroccan Dirham",
    symbol_native: "د.م.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "MAD",
    name_plural: "Moroccan dirhams",
  },
  MDL: {
    symbol: "MDL",
    name: "Moldovan Leu",
    symbol_native: "MDL",
    decimal_digits: 2,
    rounding: 0,
    code: "MDL",
    name_plural: "Moldovan lei",
  },
  MGA: {
    symbol: "MGA",
    name: "Malagasy Ariary",
    symbol_native: "MGA",
    decimal_digits: 0,
    rounding: 0,
    code: "MGA",
    name_plural: "Malagasy Ariaries",
  },
  MKD: {
    symbol: "MKD",
    name: "Macedonian Denar",
    symbol_native: "MKD",
    decimal_digits: 2,
    rounding: 0,
    code: "MKD",
    name_plural: "Macedonian denari",
  },
  MMK: {
    symbol: "MMK",
    name: "Myanma Kyat",
    symbol_native: "K",
    decimal_digits: 0,
    rounding: 0,
    code: "MMK",
    name_plural: "Myanma kyats",
  },
  MOP: {
    symbol: "MOP$",
    name: "Macanese Pataca",
    symbol_native: "MOP$",
    decimal_digits: 2,
    rounding: 0,
    code: "MOP",
    name_plural: "Macanese patacas",
  },
  MUR: {
    symbol: "MURs",
    name: "Mauritian Rupee",
    symbol_native: "MURs",
    decimal_digits: 0,
    rounding: 0,
    code: "MUR",
    name_plural: "Mauritian rupees",
  },
  MXN: {
    symbol: "MX$",
    name: "Mexican Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "MXN",
    name_plural: "Mexican pesos",
  },
  MYR: {
    symbol: "RM",
    name: "Malaysian Ringgit",
    symbol_native: "RM",
    decimal_digits: 2,
    rounding: 0,
    code: "MYR",
    name_plural: "Malaysian ringgits",
  },
  MZN: {
    symbol: "MTn",
    name: "Mozambican Metical",
    symbol_native: "MTn",
    decimal_digits: 2,
    rounding: 0,
    code: "MZN",
    name_plural: "Mozambican meticals",
  },
  NAD: {
    symbol: "N$",
    name: "Namibian Dollar",
    symbol_native: "N$",
    decimal_digits: 2,
    rounding: 0,
    code: "NAD",
    name_plural: "Namibian dollars",
  },
  NGN: {
    symbol: "₦",
    name: "Nigerian Naira",
    symbol_native: "₦",
    decimal_digits: 2,
    rounding: 0,
    code: "NGN",
    name_plural: "Nigerian nairas",
  },
  NIO: {
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    symbol_native: "C$",
    decimal_digits: 2,
    rounding: 0,
    code: "NIO",
    name_plural: "Nicaraguan córdobas",
  },
  NOK: {
    symbol: "Nkr",
    name: "Norwegian Krone",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "NOK",
    name_plural: "Norwegian kroner",
  },
  NPR: {
    symbol: "NPRs",
    name: "Nepalese Rupee",
    symbol_native: "नेरू",
    decimal_digits: 2,
    rounding: 0,
    code: "NPR",
    name_plural: "Nepalese rupees",
  },
  NZD: {
    symbol: "NZ$",
    name: "New Zealand Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "NZD",
    name_plural: "New Zealand dollars",
  },
  OMR: {
    symbol: "OMR",
    name: "Omani Rial",
    symbol_native: "ر.ع.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "OMR",
    name_plural: "Omani rials",
  },
  PAB: {
    symbol: "B/.",
    name: "Panamanian Balboa",
    symbol_native: "B/.",
    decimal_digits: 2,
    rounding: 0,
    code: "PAB",
    name_plural: "Panamanian balboas",
  },
  PEN: {
    symbol: "S/.",
    name: "Peruvian Nuevo Sol",
    symbol_native: "S/.",
    decimal_digits: 2,
    rounding: 0,
    code: "PEN",
    name_plural: "Peruvian nuevos soles",
  },
  PHP: {
    symbol: "₱",
    name: "Philippine Peso",
    symbol_native: "₱",
    decimal_digits: 2,
    rounding: 0,
    code: "PHP",
    name_plural: "Philippine pesos",
  },
  PKR: {
    symbol: "PKRs",
    name: "Pakistani Rupee",
    symbol_native: "₨",
    decimal_digits: 0,
    rounding: 0,
    code: "PKR",
    name_plural: "Pakistani rupees",
  },
  PLN: {
    symbol: "zł",
    name: "Polish Zloty",
    symbol_native: "zł",
    decimal_digits: 2,
    rounding: 0,
    code: "PLN",
    name_plural: "Polish zlotys",
  },
  PYG: {
    symbol: "₲",
    name: "Paraguayan Guarani",
    symbol_native: "₲",
    decimal_digits: 0,
    rounding: 0,
    code: "PYG",
    name_plural: "Paraguayan guaranis",
  },
  QAR: {
    symbol: "QR",
    name: "Qatari Rial",
    symbol_native: "ر.ق.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "QAR",
    name_plural: "Qatari rials",
  },
  RON: {
    symbol: "RON",
    name: "Romanian Leu",
    symbol_native: "RON",
    decimal_digits: 2,
    rounding: 0,
    code: "RON",
    name_plural: "Romanian lei",
  },
  RSD: {
    symbol: "din.",
    name: "Serbian Dinar",
    symbol_native: "дин.",
    decimal_digits: 0,
    rounding: 0,
    code: "RSD",
    name_plural: "Serbian dinars",
  },
  RUB: {
    symbol: "RUB",
    name: "Russian Ruble",
    symbol_native: "₽.",
    decimal_digits: 2,
    rounding: 0,
    code: "RUB",
    name_plural: "Russian rubles",
  },
  RWF: {
    symbol: "RWF",
    name: "Rwandan Franc",
    symbol_native: "FR",
    decimal_digits: 0,
    rounding: 0,
    code: "RWF",
    name_plural: "Rwandan francs",
  },
  SAR: {
    symbol: "SR",
    name: "Saudi Riyal",
    symbol_native: "ر.س.‏",
    decimal_digits: 2,
    rounding: 0,
    code: "SAR",
    name_plural: "Saudi riyals",
  },
  SDG: {
    symbol: "SDG",
    name: "Sudanese Pound",
    symbol_native: "SDG",
    decimal_digits: 2,
    rounding: 0,
    code: "SDG",
    name_plural: "Sudanese pounds",
  },
  SEK: {
    symbol: "Skr",
    name: "Swedish Krona",
    symbol_native: "kr",
    decimal_digits: 2,
    rounding: 0,
    code: "SEK",
    name_plural: "Swedish kronor",
  },
  SGD: {
    symbol: "S$",
    name: "Singapore Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "SGD",
    name_plural: "Singapore dollars",
  },
  SOS: {
    symbol: "Ssh",
    name: "Somali Shilling",
    symbol_native: "Ssh",
    decimal_digits: 0,
    rounding: 0,
    code: "SOS",
    name_plural: "Somali shillings",
  },
  SYP: {
    symbol: "SY£",
    name: "Syrian Pound",
    symbol_native: "ل.س.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "SYP",
    name_plural: "Syrian pounds",
  },
  THB: {
    symbol: "฿",
    name: "Thai Baht",
    symbol_native: "฿",
    decimal_digits: 2,
    rounding: 0,
    code: "THB",
    name_plural: "Thai baht",
  },
  TND: {
    symbol: "DT",
    name: "Tunisian Dinar",
    symbol_native: "د.ت.‏",
    decimal_digits: 3,
    rounding: 0,
    code: "TND",
    name_plural: "Tunisian dinars",
  },
  TOP: {
    symbol: "T$",
    name: "Tongan Paʻanga",
    symbol_native: "T$",
    decimal_digits: 2,
    rounding: 0,
    code: "TOP",
    name_plural: "Tongan paʻanga",
  },
  TRY: {
    symbol: "TL",
    name: "Turkish Lira",
    symbol_native: "TL",
    decimal_digits: 2,
    rounding: 0,
    code: "TRY",
    name_plural: "Turkish Lira",
  },
  TTD: {
    symbol: "TT$",
    name: "Trinidad and Tobago Dollar",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "TTD",
    name_plural: "Trinidad and Tobago dollars",
  },
  TWD: {
    symbol: "NT$",
    name: "New Taiwan Dollar",
    symbol_native: "NT$",
    decimal_digits: 2,
    rounding: 0,
    code: "TWD",
    name_plural: "New Taiwan dollars",
  },
  TZS: {
    symbol: "TSh",
    name: "Tanzanian Shilling",
    symbol_native: "TSh",
    decimal_digits: 0,
    rounding: 0,
    code: "TZS",
    name_plural: "Tanzanian shillings",
  },
  UAH: {
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    symbol_native: "₴",
    decimal_digits: 2,
    rounding: 0,
    code: "UAH",
    name_plural: "Ukrainian hryvnias",
  },
  UGX: {
    symbol: "USh",
    name: "Ugandan Shilling",
    symbol_native: "USh",
    decimal_digits: 0,
    rounding: 0,
    code: "UGX",
    name_plural: "Ugandan shillings",
  },
  UYU: {
    symbol: "$U",
    name: "Uruguayan Peso",
    symbol_native: "$",
    decimal_digits: 2,
    rounding: 0,
    code: "UYU",
    name_plural: "Uruguayan pesos",
  },
  UZS: {
    symbol: "UZS",
    name: "Uzbekistan Som",
    symbol_native: "UZS",
    decimal_digits: 0,
    rounding: 0,
    code: "UZS",
    name_plural: "Uzbekistan som",
  },
  VEF: {
    symbol: "Bs.F.",
    name: "Venezuelan Bolívar",
    symbol_native: "Bs.F.",
    decimal_digits: 2,
    rounding: 0,
    code: "VEF",
    name_plural: "Venezuelan bolívars",
  },
  VND: {
    symbol: "₫",
    name: "Vietnamese Dong",
    symbol_native: "₫",
    decimal_digits: 0,
    rounding: 0,
    code: "VND",
    name_plural: "Vietnamese dong",
  },

  XOF: {
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    symbol_native: "CFA",
    decimal_digits: 0,
    rounding: 0,
    code: "XOF",
    name_plural: "CFA francs BCEAO",
  },
  YER: {
    symbol: "YR",
    name: "Yemeni Rial",
    symbol_native: "ر.ي.‏",
    decimal_digits: 0,
    rounding: 0,
    code: "YER",
    name_plural: "Yemeni rials",
  },
  ZAR: {
    symbol: "R",
    name: "South African Rand",
    symbol_native: "R",
    decimal_digits: 2,
    rounding: 0,
    code: "ZAR",
    name_plural: "South African rand",
  },
  ZMK: {
    symbol: "ZK",
    name: "Zambian Kwacha",
    symbol_native: "ZK",
    decimal_digits: 0,
    rounding: 0,
    code: "ZMK",
    name_plural: "Zambian kwachas",
  },
  ZWL: {
    symbol: "ZWL$",
    name: "Zimbabwean Dollar",
    symbol_native: "ZWL$",
    decimal_digits: 0,
    rounding: 0,
    code: "ZWL",
    name_plural: "Zimbabwean Dollar",
  },*/
};
export const CURRENCY_OB = Object.values(CURRENCY_CODE);
export const DOLLAR_Rate = {
  eur: {
    code: "EUR",
    alphaCode: "EUR",
    numericCode: "978",
    name: "Euro",
    rate: 0.91014541847413,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 1.0987255219902,
  },
  gbp: {
    code: "GBP",
    alphaCode: "GBP",
    numericCode: "826",
    name: "U.K. Pound Sterling",
    rate: 0.78132920812993,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 1.279870238556,
  },
  cad: {
    code: "CAD",
    alphaCode: "CAD",
    numericCode: "124",
    name: "Canadian Dollar",
    rate: 1.3276018017716,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.75323790512002,
  },
  jpy: {
    code: "JPY",
    alphaCode: "JPY",
    numericCode: "392",
    name: "Japanese Yen",
    rate: 142.88891675499,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0069984434252146,
  },
  aud: {
    code: "AUD",
    alphaCode: "AUD",
    numericCode: "036",
    name: "Australian Dollar",
    rate: 1.5073210310442,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.66342867869842,
  },
  chf: {
    code: "CHF",
    alphaCode: "CHF",
    numericCode: "756",
    name: "Swiss Franc",
    rate: 0.87406574375554,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 1.1440787001941,
  },
  ang: {
    code: "ANG",
    alphaCode: "ANG",
    numericCode: "532",
    name: "Neth. Antillean Guilder",
    rate: 1.7900009995193,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.55865890592717,
  },
  lbp: {
    code: "LBP",
    alphaCode: "LBP",
    numericCode: "422",
    name: "Lebanese Pound",
    rate: 15021.527576793,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 6.6571125665336e-5,
  },
  myr: {
    code: "MYR",
    alphaCode: "MYR",
    numericCode: "458",
    name: "Malaysian Ringgit",
    rate: 4.5134748974878,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.22155878180614,
  },
  irr: {
    code: "IRR",
    alphaCode: "IRR",
    numericCode: "364",
    name: "Iranian rial",
    rate: 42000.045941104,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 2.3809497765843e-5,
  },
  uyu: {
    code: "UYU",
    alphaCode: "UYU",
    numericCode: "858",
    name: "Uruguayan Peso",
    rate: 37.525299491274,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.026648688046648,
  },
  jod: {
    code: "JOD",
    alphaCode: "JOD",
    numericCode: "400",
    name: "Jordanian Dinar",
    rate: 0.70902227893147,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 1.4103929167177,
  },
  php: {
    code: "PHP",
    alphaCode: "PHP",
    numericCode: "608",
    name: "Philippine Peso",
    rate: 54.799593716946,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.018248310474075,
  },
  xof: {
    code: "XOF",
    alphaCode: "XOF",
    numericCode: "952",
    name: "West African CFA Franc",
    rate: 599.26815113261,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0016687020628579,
  },
  lyd: {
    code: "LYD",
    alphaCode: "LYD",
    numericCode: "434",
    name: "Libyan Dinar",
    rate: 4.7807090937612,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.20917399080086,
  },
  nzd: {
    code: "NZD",
    alphaCode: "NZD",
    numericCode: "554",
    name: "New Zealand Dollar",
    rate: 1.6235270783537,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.61594291424694,
  },
  try: {
    code: "TRY",
    alphaCode: "TRY",
    numericCode: "949",
    name: "Turkish Lira",
    rate: 26.96094169174,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.037090692581646,
  },
  ngn: {
    code: "NGN",
    alphaCode: "NGN",
    numericCode: "566",
    name: "Nigerian Naira",
    rate: 775.35500000002,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0012897318002721,
  },
  rsd: {
    code: "RSD",
    alphaCode: "RSD",
    numericCode: "941",
    name: "Serbian Dinar",
    rate: 106.32132857985,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0094054505653489,
  },
  nok: {
    code: "NOK",
    alphaCode: "NOK",
    numericCode: "578",
    name: "Norwegian Krone",
    rate: 10.213659197415,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.097908103322372,
  },
  qar: {
    code: "QAR",
    alphaCode: "QAR",
    numericCode: "634",
    name: "Qatari Rial",
    rate: 3.6462449826453,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.2742547483122,
  },
  czk: {
    code: "CZK",
    alphaCode: "CZK",
    numericCode: "203",
    name: "Czech Koruna",
    rate: 21.828839817675,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.045810955064606,
  },
  byn: {
    code: "BYN",
    alphaCode: "BYN",
    numericCode: "933",
    name: "Belarussian Ruble",
    rate: 2.7305521791457,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.36622629211681,
  },
  ars: {
    code: "ARS",
    alphaCode: "ARS",
    numericCode: "032",
    name: "Argentine Peso",
    rate: 276.16747181964,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0036209912536444,
  },
  ves: {
    code: "VES",
    alphaCode: "VES",
    numericCode: "928",
    name: "Venezuelan Bolivar",
    rate: 29.441312037078,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.033965877564852,
  },
  bdt: {
    code: "BDT",
    alphaCode: "BDT",
    numericCode: "050",
    name: "Bangladeshi taka",
    rate: 108.86485791013,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0091857006861252,
  },
  ron: {
    code: "RON",
    alphaCode: "RON",
    numericCode: "946",
    name: "Romanian New Leu",
    rate: 4.4950495938492,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.22246695595269,
  },
  mdl: {
    code: "MDL",
    alphaCode: "MDL",
    numericCode: "498",
    name: "Moldova Lei",
    rate: 17.880474985308,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.055926925924601,
  },
  crc: {
    code: "CRC",
    alphaCode: "CRC",
    numericCode: "188",
    name: "Costa Rican Col\u00f3n",
    rate: 546.01472089314,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0018314524530845,
  },
  aed: {
    code: "AED",
    alphaCode: "AED",
    numericCode: "784",
    name: "U.A.E Dirham",
    rate: 3.6737902443578,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.27219844724009,
  },
  idr: {
    code: "IDR",
    alphaCode: "IDR",
    numericCode: "360",
    name: "Indonesian Rupiah",
    rate: 15116.794850668,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 6.6151589002732e-5,
  },
  mxn: {
    code: "MXN",
    alphaCode: "MXN",
    numericCode: "484",
    name: "Mexican Peso",
    rate: 16.807681089218,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.059496607217369,
  },
  amd: {
    code: "AMD",
    alphaCode: "AMD",
    numericCode: "051",
    name: "Armenia Dram",
    rate: 386.13982661585,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0025897354561016,
  },
  pyg: {
    code: "PYG",
    alphaCode: "PYG",
    numericCode: "600",
    name: "Paraguayan Guaran\u00ed",
    rate: 7297.8723404251,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.00013702623906706,
  },
  brl: {
    code: "BRL",
    alphaCode: "BRL",
    numericCode: "986",
    name: "Brazilian Real",
    rate: 4.7543826820868,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.210332248552,
  },
  inr: {
    code: "INR",
    alphaCode: "INR",
    numericCode: "356",
    name: "Indian Rupee",
    rate: 82.28630881227,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.012152689972781,
  },
  npr: {
    code: "NPR",
    alphaCode: "NPR",
    numericCode: "524",
    name: "Nepalese Rupee",
    rate: 131.54284714935,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0076020857208954,
  },
  xaf: {
    code: "XAF",
    alphaCode: "XAF",
    numericCode: "950",
    name: "Central African CFA Franc",
    rate: 599.26815113261,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0016687020628579,
  },
  kgs: {
    code: "KGS",
    alphaCode: "KGS",
    numericCode: "417",
    name: "Kyrgyzstan Som",
    rate: 87.707104139682,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.011401584966338,
  },
  dkk: {
    code: "DKK",
    alphaCode: "DKK",
    numericCode: "208",
    name: "Danish Krone",
    rate: 6.791535843416,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.147242100028,
  },
  lkr: {
    code: "LKR",
    alphaCode: "LKR",
    numericCode: "144",
    name: "Sri Lanka Rupee",
    rate: 329.02974628172,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0030392388873673,
  },
  tnd: {
    code: "TND",
    alphaCode: "TND",
    numericCode: "788",
    name: "Tunisian Dinar",
    rate: 3.0699034906396,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.3257431391733,
  },
  vnd: {
    code: "VND",
    alphaCode: "VND",
    numericCode: "704",
    name: "Vietnamese Dong",
    rate: 23681.173313946,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 4.2227637403891e-5,
  },
  tmt: {
    code: "TMT",
    alphaCode: "TMT",
    numericCode: "934",
    name: "New Turkmenistan Manat",
    rate: 3.4999904289734,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.28571506702472,
  },
  pkr: {
    code: "PKR",
    alphaCode: "PKR",
    numericCode: "586",
    name: "Pakistani Rupee",
    rate: 285.85975254989,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0034982189380629,
  },
  bgn: {
    code: "BGN",
    alphaCode: "BGN",
    numericCode: "975",
    name: "Bulgarian Lev",
    rate: 1.7824981620826,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.56101039612385,
  },
  rub: {
    code: "RUB",
    alphaCode: "RUB",
    numericCode: "643",
    name: "Russian Rouble",
    rate: 91.973817936442,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.010872659441963,
  },
  gel: {
    code: "GEL",
    alphaCode: "GEL",
    numericCode: "981",
    name: "Georgian lari",
    rate: 2.6256964788328,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.38085133147017,
  },
  sar: {
    code: "SAR",
    alphaCode: "SAR",
    numericCode: "682",
    name: "Saudi Riyal",
    rate: 3.7519483599897,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.266528188571,
  },
  pln: {
    code: "PLN",
    alphaCode: "PLN",
    numericCode: "985",
    name: "Polish Zloty",
    rate: 4.0352208970218,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.24781790774776,
  },
  kzt: {
    code: "KZT",
    alphaCode: "KZT",
    numericCode: "398",
    name: "Kazakhstani Tenge",
    rate: 444.59222876039,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0022492520905914,
  },
  cop: {
    code: "COP",
    alphaCode: "COP",
    numericCode: "170",
    name: "Colombian Peso",
    rate: 4035.294117647,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.00024781341107872,
  },
  bhd: {
    code: "BHD",
    alphaCode: "BHD",
    numericCode: "048",
    name: "Bahrain Dinar",
    rate: 0.376081,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 2.65900165124,
  },
  egp: {
    code: "EGP",
    alphaCode: "EGP",
    numericCode: "818",
    name: "Egyptian Pound",
    rate: 30.923739677121,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.032337615386791,
  },
  krw: {
    code: "KRW",
    alphaCode: "KRW",
    numericCode: "410",
    name: "South Korean Won",
    rate: 1286.294441886,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.00077742697739856,
  },
  dzd: {
    code: "DZD",
    alphaCode: "DZD",
    numericCode: "012",
    name: "Algerian Dinar",
    rate: 135.40160342522,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0073854369128818,
  },
  pab: {
    code: "PAB",
    alphaCode: "PAB",
    numericCode: "590",
    name: "Panamanian Balboa",
    rate: 1,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 1,
  },
  hkd: {
    code: "HKD",
    alphaCode: "HKD",
    numericCode: "344",
    name: "Hong Kong Dollar",
    rate: 7.7951572202164,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.12828477627193,
  },
  mad: {
    code: "MAD",
    alphaCode: "MAD",
    numericCode: "504",
    name: "Moroccan Dirham",
    rate: 9.8031938344929,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.10200757190799,
  },
  zar: {
    code: "ZAR",
    alphaCode: "ZAR",
    numericCode: "710",
    name: "South African Rand",
    rate: 18.14605798939,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.055108387760289,
  },
  iqd: {
    code: "IQD",
    alphaCode: "IQD",
    numericCode: "368",
    name: "Iraqi dinar",
    rate: 1309.9982088483,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.00076335982236125,
  },
  bob: {
    code: "BOB",
    alphaCode: "BOB",
    numericCode: "068",
    name: "Bolivian Boliviano",
    rate: 6.8599999999998,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.14577259475219,
  },
  kwd: {
    code: "KWD",
    alphaCode: "KWD",
    numericCode: "414",
    name: "Kuwaiti Dinar",
    rate: 0.30711972312914,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 3.2560592000127,
  },
  thb: {
    code: "THB",
    alphaCode: "THB",
    numericCode: "764",
    name: "Thai Baht",
    rate: 34.237808506718,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.029207476868848,
  },
  twd: {
    code: "TWD",
    alphaCode: "TWD",
    numericCode: "901",
    name: "New Taiwan Dollar ",
    rate: 31.543763142574,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.031701987980322,
  },
  uzs: {
    code: "UZS",
    alphaCode: "UZS",
    numericCode: "860",
    name: "Uzbekistan Sum",
    rate: 11600.241086156,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 8.6205104926088e-5,
  },
  omr: {
    code: "OMR",
    alphaCode: "OMR",
    numericCode: "512",
    name: "Omani Rial",
    rate: 0.38474979769178,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 2.599091685036,
  },
  ils: {
    code: "ILS",
    alphaCode: "ILS",
    numericCode: "376",
    name: "Israeli New Sheqel",
    rate: 3.6503219238753,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.27394844094692,
  },
  pen: {
    code: "PEN",
    alphaCode: "PEN",
    numericCode: "604",
    name: "Peruvian Nuevo Sol",
    rate: 3.6301880732727,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.27546782145049,
  },
  tjs: {
    code: "TJS",
    alphaCode: "TJS",
    numericCode: "972",
    name: "Tajikistan Ruble",
    rate: 10.919585535549,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.091578567404823,
  },
  sek: {
    code: "SEK",
    alphaCode: "SEK",
    numericCode: "752",
    name: "Swedish Krona",
    rate: 10.611131968751,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.094240652453002,
  },
  sgd: {
    code: "SGD",
    alphaCode: "SGD",
    numericCode: "702",
    name: "Singapore Dollar",
    rate: 1.334381415307,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.74941091694531,
  },
  huf: {
    code: "HUF",
    alphaCode: "HUF",
    numericCode: "348",
    name: "Hungarian Forint",
    rate: 354.78110786132,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0028186393746504,
  },
  uah: {
    code: "UAH",
    alphaCode: "UAH",
    numericCode: "980",
    name: "Ukrainian Hryvnia",
    rate: 36.598894384396,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.027323229753802,
  },
  clp: {
    code: "CLP",
    alphaCode: "CLP",
    numericCode: "152",
    name: "Chilean Peso",
    rate: 839.48676102896,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.00119120401467,
  },
  dop: {
    code: "DOP",
    alphaCode: "DOP",
    numericCode: "214",
    name: "Dominican Peso",
    rate: 56.0535801073,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.017840073695307,
  },
  cny: {
    code: "CNY",
    alphaCode: "CNY",
    numericCode: "156",
    name: "Chinese Yuan",
    rate: 7.1684775343441,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.13949963506323,
  },
  isk: {
    code: "ISK",
    alphaCode: "ISK",
    numericCode: "352",
    name: "Icelandic Krona",
    rate: 131.53451904608,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0076025670466752,
  },
  azn: {
    code: "AZN",
    alphaCode: "AZN",
    numericCode: "944",
    name: "Azerbaijan Manat",
    rate: 1.6979982633971,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.58892875308326,
  },
  htg: {
    code: "HTG",
    alphaCode: "HTG",
    numericCode: "332",
    name: "Haitian gourde",
    rate: 135.27903766515,
    date: "Tue, 1 Aug 2023 23:55:01 GMT",
    inverseRate: 0.0073921282798836,
  },
};
